In [3]:
!pip uninstall -y transformers -q
!pip install transformers==4.41.0 liqfit sentencepiece --no-cache-dir -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.8/43.8 kB 4.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 98.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 229.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 187.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 220.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 168.2 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gradio 6.19.0 requires huggingface-hub<2.0,>=1.2.0, but you have huggingface-hub 0.36.2 which is incompatible.

In [1]:
from transformers import pipeline

classificador = pipeline('zero-shot-classification', model='facebook/bart-large-mnli')

categorias = ['eletronics', 'food', 'toys', 'books']

predicao = classificador('''
Latest model of smartphone with 5G connectivity and 128GB internal storage
''', candidate_labels=categorias)

predicao

The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.

0it [00:00, ?it/s]

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

{'sequence': '\nLatest model of smartphone with 5G connectivity and 128GB internal storage\n',
 'labels': ['eletronics', 'books', 'food', 'toys'],
 'scores': [0.8751646876335144,
  0.044109657406806946,
  0.043100371956825256,
  0.0376252718269825]}

In [2]:
from liqfit.pipeline import ZeroShotClassificationPipeline
from liqfit.models import T5ForZeroShotClassification
from transformers import T5Tokenizer

modelo = T5ForZeroShotClassification.from_pretrained('knowledgator/comprehend_it-multilingual-t5-base')
tokenizador = T5Tokenizer.from_pretrained('knowledgator/comprehend_it-multilingual-t5-base')
classificador = ZeroShotClassificationPipeline(model=modelo, tokenizer=tokenizador,
                                                      hypothesis_template = '{}', encoder_decoder = True)

config.json: 0.00B [00:00, ?B/s]

You are using a model of type T5 to instantiate a model of type t5. This is not supported for all configurations of models and can yield errors.

pytorch_model.bin:   0%|          | 0.00/1.56G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/477 [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/4.31M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/74.0 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/16.3M [00:00<?, ?B/s]

You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565

In [4]:
descricao = '''Este water gel leve e refrescante, proporciona hidratação imediata que ajuda a aliviar o
repuxamento e aspereza da pele sensível.'''
categorias_candidatas = ['beleza', 'cozinha', 'livros']
resultado = classificador(descricao, categorias_candidatas, multi_label = False)
resultado

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.

{'sequence': 'Este water gel leve e refrescante, proporciona hidratação imediata que ajuda a aliviar o \nrepuxamento e aspereza da pele sensível.',
 'labels': ['beleza', 'livros', 'cozinha'],
 'scores': [0.9386342167854309, 0.04146720468997955, 0.01989862322807312]}

In [5]:
import pandas as pd

In [7]:
resultado = pd.DataFrame(resultado).drop(['sequence'], axis = 1)
resultado

    labels    scores
0   beleza  0.938634
1   livros  0.041467
2  cozinha  0.019899

In [8]:
descricao = '''A fritadeira eletrica sem óleo start fry da elgin possui um design único, capacidade para até 3,5 litros,
            potência de 1400w e revestimento antiaderente. Seu sistema de circulação de ar ultra rápido frita e economiza energia.
            Sua grelha de fritura é removível e super fácil de limpar. Ela conta com uma proteção contra super aquecimento.
            Possui controle de temperatura de 80°c a 200°c que permite você programar a temperatura de preparo para cada tipo de alimento,
            timer para até 60 minutos com aviso sonoro e desligamento automático, assim você pode deixar preparando sua refeição
            enquanto realiza outras tarefas.'''

categorias_candidatas = ['beleza', 'cozinha', 'livros']
resultado = classificador(descricao, categorias_candidatas, multi_label = False)
resultado = pd.DataFrame(resultado).drop(['sequence'], axis = 1)
resultado

    labels    scores
0  cozinha  0.709798
1   beleza  0.236621
2   livros  0.053581

In [9]:
dados = pd.read_csv('https://raw.githubusercontent.com/alura-cursos/hugging_face/main/Dados/descricoes_produtos.csv')
dados

                                            Descrição
0   Liquidificador de alta potência com jarra de v...
1   Forno Micro-ondas de 20 litros, com menu desco...
2   Máquina de café espresso com reservatório de á...
3   Torradeira com capacidade para quatro fatias e...
4   Panela elétrica multifuncional que cozinha, as...
5   Smartphone com 128GB de armazenamento e câmera...
6   Smartwatch monitoramento de passos, frequência...
7   Notebook gamer com placa de vídeo potente e te...
8   Smartphone com tela super retina XDR de 6,7 po...
9   Câmera digital com zoom óptico de 20x e vídeos...
10  Fone de ouvido sem fio com cancelamento de ruí...
11  Carregador portátil com capacidade de 20000mAh...
12  Creme hidratante com ácido hialurônico para to...
13  Shampoo fortalecedor com biotina e minerais pa...
14  Paleta de maquiagem com 24 cores, incluindo op...
15  vPerfume feminino com notas de jasmim e sândal...
16  Kit de barbear com creme, pós-barba e lâminas ...
17  Sérum facial anti-idade com vitamina C e ácido...
18  Máscara facial de argila purificante, ideal pa...
19  Quebra-cabeça de 1000 peças com imagem de pais...
20  Kit de ciências para crianças com experiências...
21  Jogo de tabuleiro clássico de estratégia para ...

In [10]:
categorias = ['eletrodomésticos', 'eletronicos', 'beleza', 'brinquedos']

def categorizar(descricao):
  resultado = classificador(descricao, categorias, multi_label = False)
  categoria_max = max(zip(resultado['labels'], resultado['scores']), key = lambda x: x[1])[0]
  return categoria_max

dados['categoria'] = dados['Descrição'].apply(categorizar)